name: Django CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Tests
      run: |
        python manage.py test
    - name: Zip Release
      uses: TheDoctor0/zip-release@0.7.1
      with:
        filename: release.zip
        path: .
        directory: .
        type: zip
    - name: copy file via ssh key
      uses: appleboy/scp-action@v0.1.4
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.USERNAME }}
        port: ${{ secrets.EC2_PORT }}
        key: ${{ secrets.JH_PEM }}
        source: "release.zip"
        target: /home/ec2-user
    - name: ssh command
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.JH_PEM }}
        port: ${{ secrets.EC2_PORT }}
        script: /home/ec2-user/deploy.sh
